-- Categorías (orden fijo: ids 1..12, tabla vacía en esta migración)
INSERT INTO categorias (nombre, descripcion) VALUES
    ('Entradas frías',      'Platos fríos para abrir el apetito'),
    ('Entradas calientes',  'Platos calientes para abrir el apetito'),
    ('Sopas y caldos',      'Sopas, caldos y chupes tradicionales'),
    ('Ceviches',            'Pescados y mariscos marinados en limón'),
    ('Criollos',            'Platos de fondo de la cocina criolla peruana'),
    ('Pescados y mariscos', 'Platos de fondo a base de pescados y mariscos'),
    ('Carnes',              'Platos de fondo a base de carnes rojas y aves'),
    ('Pastas',              'Pastas y platos de inspiración italiana'),
    ('Chifa',               'Cocina chino-peruana'),
    ('Guarniciones',        'Acompañamientos y guarniciones'),
    ('Postres',             'Postres tradicionales y de autor'),
    ('Bebidas',             'Bebidas frías y calientes');

-- Generación masiva de platos (20,500 filas) con generate_series, sin INSERT por fila.
-- Cada nombre se arma combinando un sustantivo de la categoría con un calificativo;
-- solo se agrega un sufijo numérico cuando el combo (sustantivo, calificativo) ya se
-- usó en una vuelta anterior del ciclo, para no violar UNIQUE (categoria_id, nombre).
WITH cats (id, nombre, nouns, quals, cnt, pmin, pmax) AS (
    VALUES
    (1::bigint, 'Entradas frías'::text,
        ARRAY['Causa limeña','Causa de pollo','Causa de atún','Tiradito','Palta rellena',
              'Ensalada rusa','Choclo con queso','Papa a la huancaína','Ocopa arequipeña',
              'Solterito','Rocoto relleno','Anticuchos de champiñón']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        1200, 10.00, 22.00),
    (2, 'Entradas calientes',
        ARRAY['Anticuchos','Chicharrón de pescado','Choritos a la chalaca','Conchitas a la parmesana',
              'Tequeños','Yuquitas fritas','Camote frito','Chicharrón de pollo','Rocoto relleno',
              'Papa rellena']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        1300, 12.00, 25.00),
    (3, 'Sopas y caldos',
        ARRAY['Caldo de gallina','Chupe de camarones','Parihuela','Sopa criolla','Aguadito de pollo',
              'Chairo','Caldo verde','Sopa a la minuta','Chupe de pescado','Consomé de pollo']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        1000, 14.00, 28.00),
    (4, 'Ceviches',
        ARRAY['Ceviche de pescado','Ceviche mixto','Ceviche de camarones','Ceviche de pulpo',
              'Ceviche de conchas negras','Tiradito de pescado','Ceviche clásico','Ceviche de mariscos',
              'Ceviche nikkei','Leche de tigre']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        1100, 22.00, 45.00),
    (5, 'Criollos',
        ARRAY['Lomo saltado','Ají de gallina','Seco de res','Seco de cordero','Tacu tacu',
              'Carapulcra','Arroz con pollo','Estofado de pollo','Cau cau','Escabeche de pollo',
              'Adobo de cerdo','Chicharrón de chancho','Tallarín saltado','Bistec','Anticuchos de corazón']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        3800, 25.00, 75.00),
    (6, 'Pescados y mariscos',
        ARRAY['Pescado a lo macho','Jalea mixta','Arroz con mariscos','Chicharrón de calamar',
              'Pescado a la plancha','Sudado de pescado','Pescado frito','Tiradito de mariscos',
              'Trucha frita','Langostinos al ajillo','Pulpo al olivo','Conchitas a la parmesana']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        2800, 28.00, 85.00),
    (7, 'Carnes',
        ARRAY['Bife','Churrasco','Costillar de cerdo','Parrilla mixta','Chuleta de cerdo',
              'Lomo fino','Bistec apanado','Asado de tira','Anticuchos de res','Chicharrón de res',
              'Cordero','Pollo a la brasa']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        2800, 30.00, 90.00),
    (8, 'Pastas',
        ARRAY['Tallarines verdes','Fettuccine alfredo','Ravioles de ricotta','Lasaña de carne',
              'Tallarines a la huancaína','Spaghetti a la boloñesa','Canelones de pollo',
              'Tallarines saltados','Ñoquis a la crema','Penne al pesto']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        1200, 22.00, 45.00),
    (9, 'Chifa',
        ARRAY['Arroz chaufa','Tallarín saltado','Pollo chi jau kay','Chancho asado con tamarindo',
              'Wantán frito','Sopa wantán','Kam lu wantán','Pollo con piña','Chaufa de mariscos',
              'Tipakay de pollo','Lomo saltado chifa','Arroz relleno']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        2000, 20.00, 48.00),
    (10, 'Guarniciones',
        ARRAY['Papas fritas','Arroz blanco','Yuca frita','Tostones','Ensalada mixta','Puré de papas',
              'Camote frito','Choclo desgranado','Frejoles','Tallarín al ajo']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        900, 8.00, 18.00),
    (11, 'Postres',
        ARRAY['Suspiro a la limeña','Mazamorra morada','Arroz con leche','Picarones','Tres leches',
              'Crema volteada','Alfajores','Turrón de doña Pepa','Cheesecake de maracuyá',
              'Torta helada','Flan de vainilla','Keke de chocolate']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        1200, 12.00, 30.00),
    (12, 'Bebidas',
        ARRAY['Chicha morada','Limonada','Maracuyá sour','Emoliente','Jugo de naranja','Café pasado',
              'Té helado','Agua de manzana','Refresco de piña','Pisco sour','Cerveza artesanal',
              'Infusión de hierbas']::text[],
        ARRAY['clásico','criollo','de la casa','a lo pobre','al ajo','en salsa de rocoto',
              'especial','tradicional','casero','a la parrilla','gourmet','del chef']::text[],
        1200, 8.00, 25.00)
)
INSERT INTO platos (categoria_id, nombre, descripcion, precio, disponible,
                     tiempo_preparacion_min, calorias, creado_en, actualizado_en)
SELECT
    c.id,
    c.nouns[((gs.i - 1) % array_length(c.nouns, 1)) + 1]
        || ' ' || c.quals[(((gs.i - 1) / array_length(c.nouns, 1)) % array_length(c.quals, 1)) + 1]
        || CASE
               WHEN ((gs.i - 1) / (array_length(c.nouns, 1) * array_length(c.quals, 1))) > 0
               THEN ' ' || (((gs.i - 1) / (array_length(c.nouns, 1) * array_length(c.quals, 1))) + 1)::text
               ELSE ''
           END,
    'Delicioso plato de la categoría ' || c.nombre,
    round((c.pmin + random() * (c.pmax - c.pmin))::numeric, 2),
    (random() < 0.85),
    (floor(random() * 41) + 5)::int,
    (floor(random() * 1111) + 90)::int,
    now(),
    now()
FROM cats c
CROSS JOIN LATERAL generate_series(1, c.cnt::int) AS gs(i);
